services:
  sample-app:
    image: ghcr.io/nayetdet/http-load-balancer:sample-app
    pull_policy: always
    labels:
      http-load-balancer.target: "true"
    cpus: "0.50"
    mem_limit: 256m
    deploy:
      replicas: 3
    ports:
      - "3000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:3000/health')"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
