services:
  sample-app:
    image: ghcr.io/nayetdet/http-load-balancer:sample-app
    pull_policy: always
    labels:
      http-load-balancer.target: "true"
    deploy:
      replicas: 3
    ports:
      - "3000"
