apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-load-balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-load-balancer
  template:
    metadata:
      labels:
        app: http-load-balancer
    spec:
      containers:
        - name: http-load-balancer
          image: ghcr.io/nayetdet/http-load-balancer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 9090
