name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-http-load-balancer:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
    with:
      tag: latest
      dockerfile: packages/http_load_balancer/Dockerfile

  build-http-target-discovery:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
    with:
      tag: http-target-discovery
      dockerfile: packages/http_target_discovery/Dockerfile

  build-sample-app:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
    with:
      tag: sample-app
      dockerfile: packages/sample_app/Dockerfile

  postbuild:
    needs: [build-http-load-balancer, build-http-target-discovery, build-sample-app]
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Clean up old GHCR images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          min-versions-to-keep: 5
          delete-only-untagged-versions: true
