name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-http-load-balancer:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
    with:
      tag: latest
      dockerfile: packages/http_load_balancer/Dockerfile

  build-http-target-discovery:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
    with:
      tag: http-target-discovery
      dockerfile: packages/http_target_discovery/Dockerfile

  build-sample-app:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
    with:
      tag: sample-app
      dockerfile: packages/sample_app/Dockerfile
